### ISSUE TITLE
getZones fails on circular zones

### ISSUE THREAD

**Issue by bergerr2** [presence-insights/pi-clientsdk-android#24]
PIZone always tries to get the coordinates from a 2d array for a polygon, but since a circle only has a 1d array for it's center it crashes. PIZone probably needs new properties for zone type, center, and radius so it can handle circles.

java.lang.ClassCastException: java.lang.Long cannot be cast to com.ibm.json.java.JSONArray
                                                                                             at com.ibm.pisdk.doctypes.PIZone.getPolygonsFromJson(PIZone.java:59)
                                                                                             at com.ibm.pisdk.doctypes.PIZone.<init>(PIZone.java:50)
                                                                                             at com.ibm.pisdk.PIAPIAdapter$10.onComplete(PIAPIAdapter.java:354)
                                                                                             at com.ibm.pisdk.PIAPIAdapter$ApiTask.onPostExecute(PIAPIAdapter.java:784)
                                                                                             at com.ibm.pisdk.PIAPIAdapter$ApiTask.onPostExecute(PIAPIAdapter.java:691)
                                                                                             at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                                             at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                                             at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mbillau** [comment]
see https://github.com/presence-insights/pi-clientsdk-android/blob/master/pi-sdk/src/main/java/com/ibm/pisdk/doctypes/PIZone.java#L58

We need to check for this issue in iOS, and add this case to the test app.
